2014-07-17 00:23:36 Error: [MissingDatasourceConfigException] The datasource configuration "default" was not found in database.php
Exception Attributes: array (
  'config' => 'default',
)
Request URL: /portal/users/login
Stack Trace:
#0 C:\xampp\htdocs\portal\lib\Cake\Model\ConnectionManager.php(91): ConnectionManager::_getConnectionObject('default')
#1 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(3479): ConnectionManager::getDataSource('default')
#2 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(1128): Model->setDataSource('default')
#3 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(3501): Model->setSource('users')
#4 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(1357): Model->getDataSource()
#5 C:\xampp\htdocs\portal\lib\Cake\View\Helper\FormHelper.php(207): Model->schema()
#6 C:\xampp\htdocs\portal\lib\Cake\View\Helper\FormHelper.php(459): FormHelper->_introspectModel('User', 'fields')
#7 C:\xampp\htdocs\portal\app\View\Users\login.ctp(5): FormHelper->create('User', Array)
#8 C:\xampp\htdocs\portal\lib\Cake\View\View.php(943): include('C:\\xampp\\htdocs...')
#9 C:\xampp\htdocs\portal\lib\Cake\View\View.php(905): View->_evaluate('C:\\xampp\\htdocs...', Array)
#10 C:\xampp\htdocs\portal\lib\Cake\View\View.php(465): View->_render('C:\\xampp\\htdocs...')
#11 C:\xampp\htdocs\portal\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#12 C:\xampp\htdocs\portal\lib\Cake\Routing\Dispatcher.php(197): Controller->render()
#13 C:\xampp\htdocs\portal\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#14 C:\xampp\htdocs\portal\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#15 {main}
2014-07-17 00:23:56 Error: [MissingDatasourceConfigException] The datasource configuration "default" was not found in database.php
Exception Attributes: array (
  'config' => 'default',
)
Request URL: /portal/users/login
Stack Trace:
#0 C:\xampp\htdocs\portal\lib\Cake\Model\ConnectionManager.php(91): ConnectionManager::_getConnectionObject('default')
#1 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(3479): ConnectionManager::getDataSource('default')
#2 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(1128): Model->setDataSource('default')
#3 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(3501): Model->setSource('users')
#4 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(1357): Model->getDataSource()
#5 C:\xampp\htdocs\portal\lib\Cake\View\Helper\FormHelper.php(207): Model->schema()
#6 C:\xampp\htdocs\portal\lib\Cake\View\Helper\FormHelper.php(459): FormHelper->_introspectModel('User', 'fields')
#7 C:\xampp\htdocs\portal\app\View\Users\login.ctp(5): FormHelper->create('User', Array)
#8 C:\xampp\htdocs\portal\lib\Cake\View\View.php(943): include('C:\\xampp\\htdocs...')
#9 C:\xampp\htdocs\portal\lib\Cake\View\View.php(905): View->_evaluate('C:\\xampp\\htdocs...', Array)
#10 C:\xampp\htdocs\portal\lib\Cake\View\View.php(465): View->_render('C:\\xampp\\htdocs...')
#11 C:\xampp\htdocs\portal\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#12 C:\xampp\htdocs\portal\lib\Cake\Routing\Dispatcher.php(197): Controller->render()
#13 C:\xampp\htdocs\portal\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#14 C:\xampp\htdocs\portal\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#15 {main}
2014-07-17 00:24:00 Error: [MissingDatasourceConfigException] The datasource configuration "default" was not found in database.php
Exception Attributes: array (
  'config' => 'default',
)
Request URL: /portal/users/login
Stack Trace:
#0 C:\xampp\htdocs\portal\lib\Cake\Model\ConnectionManager.php(91): ConnectionManager::_getConnectionObject('default')
#1 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(3479): ConnectionManager::getDataSource('default')
#2 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(1128): Model->setDataSource('default')
#3 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(3501): Model->setSource('users')
#4 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(1357): Model->getDataSource()
#5 C:\xampp\htdocs\portal\lib\Cake\View\Helper\FormHelper.php(207): Model->schema()
#6 C:\xampp\htdocs\portal\lib\Cake\View\Helper\FormHelper.php(459): FormHelper->_introspectModel('User', 'fields')
#7 C:\xampp\htdocs\portal\app\View\Users\login.ctp(5): FormHelper->create('User', Array)
#8 C:\xampp\htdocs\portal\lib\Cake\View\View.php(943): include('C:\\xampp\\htdocs...')
#9 C:\xampp\htdocs\portal\lib\Cake\View\View.php(905): View->_evaluate('C:\\xampp\\htdocs...', Array)
#10 C:\xampp\htdocs\portal\lib\Cake\View\View.php(465): View->_render('C:\\xampp\\htdocs...')
#11 C:\xampp\htdocs\portal\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#12 C:\xampp\htdocs\portal\lib\Cake\Routing\Dispatcher.php(197): Controller->render()
#13 C:\xampp\htdocs\portal\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#14 C:\xampp\htdocs\portal\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#15 {main}
2014-07-17 00:27:15 Error: [MissingDatasourceConfigException] The datasource configuration "default" was not found in database.php
Exception Attributes: array (
  'config' => 'default',
)
Request URL: /portal/users/login
Stack Trace:
#0 C:\xampp\htdocs\portal\lib\Cake\Model\ConnectionManager.php(91): ConnectionManager::_getConnectionObject('default')
#1 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(3479): ConnectionManager::getDataSource('default')
#2 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(1128): Model->setDataSource('default')
#3 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(3501): Model->setSource('users')
#4 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(1357): Model->getDataSource()
#5 C:\xampp\htdocs\portal\lib\Cake\View\Helper\FormHelper.php(207): Model->schema()
#6 C:\xampp\htdocs\portal\lib\Cake\View\Helper\FormHelper.php(459): FormHelper->_introspectModel('User', 'fields')
#7 C:\xampp\htdocs\portal\app\View\Users\login.ctp(5): FormHelper->create('User', Array)
#8 C:\xampp\htdocs\portal\lib\Cake\View\View.php(943): include('C:\\xampp\\htdocs...')
#9 C:\xampp\htdocs\portal\lib\Cake\View\View.php(905): View->_evaluate('C:\\xampp\\htdocs...', Array)
#10 C:\xampp\htdocs\portal\lib\Cake\View\View.php(465): View->_render('C:\\xampp\\htdocs...')
#11 C:\xampp\htdocs\portal\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#12 C:\xampp\htdocs\portal\lib\Cake\Routing\Dispatcher.php(197): Controller->render()
#13 C:\xampp\htdocs\portal\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#14 C:\xampp\htdocs\portal\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#15 {main}
2014-07-17 00:59:13 Error: [MissingHelperException] Helper class AuthHelper could not be found.
Exception Attributes: array (
  'class' => 'AuthHelper',
  'plugin' => false,
)
Request URL: /portal/news/edit/2
Stack Trace:
#0 C:\xampp\htdocs\portal\lib\Cake\View\HelperCollection.php(63): HelperCollection->load('Auth')
#1 C:\xampp\htdocs\portal\lib\Cake\View\View.php(832): HelperCollection->__isset('Auth')
#2 C:\xampp\htdocs\portal\app\View\Layouts\default.ctp(283): View->__get('Auth')
#3 C:\xampp\htdocs\portal\lib\Cake\View\View.php(943): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\portal\lib\Cake\View\View.php(905): View->_evaluate('C:\\xampp\\htdocs...', Array)
#5 C:\xampp\htdocs\portal\lib\Cake\View\View.php(536): View->_render('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\portal\lib\Cake\View\View.php(473): View->renderLayout('', 'default')
#7 C:\xampp\htdocs\portal\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#8 C:\xampp\htdocs\portal\lib\Cake\Routing\Dispatcher.php(197): Controller->render()
#9 C:\xampp\htdocs\portal\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(NewsController), Object(CakeRequest), Object(CakeResponse))
#10 C:\xampp\htdocs\portal\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
2014-07-17 02:10:31 Error: [MissingTableException] Table sections for model Section was not found in datasource default.
Exception Attributes: array (
  'table' => 'sections',
  'class' => 'Section',
  'ds' => 'default',
)
Request URL: /portal/sections
Stack Trace:
#0 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(3501): Model->setSource('sections')
#1 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(2905): Model->getDataSource()
#2 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(2877): Model->_readDataSource('all', Array)
#3 C:\xampp\htdocs\portal\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#4 C:\xampp\htdocs\portal\app\Controller\SectionsController.php(27): PaginatorComponent->paginate()
#5 [internal function]: SectionsController->index()
#6 C:\xampp\htdocs\portal\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(SectionsController), Array)
#7 C:\xampp\htdocs\portal\lib\Cake\Routing\Dispatcher.php(190): Controller->invokeAction(Object(CakeRequest))
#8 C:\xampp\htdocs\portal\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(SectionsController), Object(CakeRequest), Object(CakeResponse))
#9 C:\xampp\htdocs\portal\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2014-07-17 02:10:38 Error: [MissingTableException] Table sections for model Section was not found in datasource default.
Exception Attributes: array (
  'table' => 'sections',
  'class' => 'Section',
  'ds' => 'default',
)
Request URL: /portal/categories
Stack Trace:
#0 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(3501): Model->setSource('sections')
#1 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(1357): Model->getDataSource()
#2 C:\xampp\htdocs\portal\lib\Cake\Model\Datasource\DboSource.php(2481): Model->schema()
#3 C:\xampp\htdocs\portal\lib\Cake\Model\Datasource\DboSource.php(1706): DboSource->fields(Object(Section), 'Section', '')
#4 C:\xampp\htdocs\portal\lib\Cake\Model\Datasource\DboSource.php(1093): DboSource->generateAssociationQuery(Object(Category), Object(Section), 'belongsTo', 'Section', Array, Array, false)
#5 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(2905): DboSource->read(Object(Category), Array)
#6 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(2877): Model->_readDataSource('all', Array)
#7 C:\xampp\htdocs\portal\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#8 C:\xampp\htdocs\portal\app\Controller\CategoriesController.php(27): PaginatorComponent->paginate()
#9 [internal function]: CategoriesController->index()
#10 C:\xampp\htdocs\portal\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(CategoriesController), Array)
#11 C:\xampp\htdocs\portal\lib\Cake\Routing\Dispatcher.php(190): Controller->invokeAction(Object(CakeRequest))
#12 C:\xampp\htdocs\portal\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(CategoriesController), Object(CakeRequest), Object(CakeResponse))
#13 C:\xampp\htdocs\portal\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
2014-07-17 02:10:43 Error: [MissingTableException] Table sections for model Section was not found in datasource default.
Exception Attributes: array (
  'table' => 'sections',
  'class' => 'Section',
  'ds' => 'default',
)
Request URL: /portal/categories
Stack Trace:
#0 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(3501): Model->setSource('sections')
#1 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(1357): Model->getDataSource()
#2 C:\xampp\htdocs\portal\lib\Cake\Model\Datasource\DboSource.php(2481): Model->schema()
#3 C:\xampp\htdocs\portal\lib\Cake\Model\Datasource\DboSource.php(1706): DboSource->fields(Object(Section), 'Section', '')
#4 C:\xampp\htdocs\portal\lib\Cake\Model\Datasource\DboSource.php(1093): DboSource->generateAssociationQuery(Object(Category), Object(Section), 'belongsTo', 'Section', Array, Array, false)
#5 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(2905): DboSource->read(Object(Category), Array)
#6 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(2877): Model->_readDataSource('all', Array)
#7 C:\xampp\htdocs\portal\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#8 C:\xampp\htdocs\portal\app\Controller\CategoriesController.php(27): PaginatorComponent->paginate()
#9 [internal function]: CategoriesController->index()
#10 C:\xampp\htdocs\portal\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(CategoriesController), Array)
#11 C:\xampp\htdocs\portal\lib\Cake\Routing\Dispatcher.php(190): Controller->invokeAction(Object(CakeRequest))
#12 C:\xampp\htdocs\portal\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(CategoriesController), Object(CakeRequest), Object(CakeResponse))
#13 C:\xampp\htdocs\portal\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
2014-07-22 20:15:00 Error: Fatal Error (4): syntax error, unexpected '<<' (T_SL) in [C:\xampp\htdocs\portal\app\View\Layouts\default.ctp, line 20]
2014-07-22 20:15:00 Error: [FatalErrorException] syntax error, unexpected '<<' (T_SL)
Request URL: /portal/users/login
Stack Trace:
#0 C:\xampp\htdocs\portal\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 20)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 20, Array)
#2 C:\xampp\htdocs\portal\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 20, Array)
#3 C:\xampp\htdocs\portal\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-07-22 20:15:13 Error: Fatal Error (4): syntax error, unexpected '<<' (T_SL) in [C:\xampp\htdocs\portal\app\View\Layouts\default.ctp, line 20]
2014-07-22 20:15:13 Error: [FatalErrorException] syntax error, unexpected '<<' (T_SL)
Request URL: /portal/users/login
Stack Trace:
#0 C:\xampp\htdocs\portal\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 20)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 20, Array)
#2 C:\xampp\htdocs\portal\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 20, Array)
#3 C:\xampp\htdocs\portal\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-07-22 20:25:40 Error: [MissingTableException] Table sections for model Section was not found in datasource default.
Exception Attributes: array (
  'table' => 'sections',
  'class' => 'Section',
  'ds' => 'default',
)
Request URL: /portal/categories
Stack Trace:
#0 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(3501): Model->setSource('sections')
#1 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(1357): Model->getDataSource()
#2 C:\xampp\htdocs\portal\lib\Cake\Model\Datasource\DboSource.php(2481): Model->schema()
#3 C:\xampp\htdocs\portal\lib\Cake\Model\Datasource\DboSource.php(1706): DboSource->fields(Object(Section), 'Section', '')
#4 C:\xampp\htdocs\portal\lib\Cake\Model\Datasource\DboSource.php(1093): DboSource->generateAssociationQuery(Object(Category), Object(Section), 'belongsTo', 'Section', Array, Array, false)
#5 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(2905): DboSource->read(Object(Category), Array)
#6 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(2877): Model->_readDataSource('all', Array)
#7 C:\xampp\htdocs\portal\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#8 C:\xampp\htdocs\portal\app\Controller\CategoriesController.php(27): PaginatorComponent->paginate()
#9 [internal function]: CategoriesController->index()
#10 C:\xampp\htdocs\portal\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(CategoriesController), Array)
#11 C:\xampp\htdocs\portal\lib\Cake\Routing\Dispatcher.php(190): Controller->invokeAction(Object(CakeRequest))
#12 C:\xampp\htdocs\portal\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(CategoriesController), Object(CakeRequest), Object(CakeResponse))
#13 C:\xampp\htdocs\portal\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
2014-07-22 20:29:01 Error: [MissingTableException] Table sections for model Section was not found in datasource default.
Exception Attributes: array (
  'table' => 'sections',
  'class' => 'Section',
  'ds' => 'default',
)
Request URL: /portal/categories
Stack Trace:
#0 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(3501): Model->setSource('sections')
#1 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(1357): Model->getDataSource()
#2 C:\xampp\htdocs\portal\lib\Cake\Model\Datasource\DboSource.php(2481): Model->schema()
#3 C:\xampp\htdocs\portal\lib\Cake\Model\Datasource\DboSource.php(1706): DboSource->fields(Object(Section), 'Section', '')
#4 C:\xampp\htdocs\portal\lib\Cake\Model\Datasource\DboSource.php(1093): DboSource->generateAssociationQuery(Object(Category), Object(Section), 'belongsTo', 'Section', Array, Array, false)
#5 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(2905): DboSource->read(Object(Category), Array)
#6 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(2877): Model->_readDataSource('all', Array)
#7 C:\xampp\htdocs\portal\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#8 C:\xampp\htdocs\portal\app\Controller\CategoriesController.php(27): PaginatorComponent->paginate()
#9 [internal function]: CategoriesController->index()
#10 C:\xampp\htdocs\portal\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(CategoriesController), Array)
#11 C:\xampp\htdocs\portal\lib\Cake\Routing\Dispatcher.php(190): Controller->invokeAction(Object(CakeRequest))
#12 C:\xampp\htdocs\portal\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(CategoriesController), Object(CakeRequest), Object(CakeResponse))
#13 C:\xampp\htdocs\portal\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
2014-07-22 21:19:56 Error: Fatal Error (1): Unsupported operand types in [C:\xampp\htdocs\portal\lib\Cake\View\Helper\FormHelper.php, line 1780]
2014-07-22 21:19:56 Error: [FatalErrorException] Unsupported operand types
Request URL: /portal/groups/edit/1
Stack Trace:
#0 C:\xampp\htdocs\portal\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 1780)
#1 [internal function]: ErrorHandler::handleError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 1780, Array)
#2 C:\xampp\htdocs\portal\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 1780, Array)
#3 C:\xampp\htdocs\portal\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-07-22 21:27:11 Error: [MissingTableException] Table sections for model Section was not found in datasource default.
Exception Attributes: array (
  'table' => 'sections',
  'class' => 'Section',
  'ds' => 'default',
)
Request URL: /portal/sections
Stack Trace:
#0 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(3501): Model->setSource('sections')
#1 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(2905): Model->getDataSource()
#2 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(2877): Model->_readDataSource('all', Array)
#3 C:\xampp\htdocs\portal\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#4 C:\xampp\htdocs\portal\app\Controller\SectionsController.php(27): PaginatorComponent->paginate()
#5 [internal function]: SectionsController->index()
#6 C:\xampp\htdocs\portal\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(SectionsController), Array)
#7 C:\xampp\htdocs\portal\lib\Cake\Routing\Dispatcher.php(190): Controller->invokeAction(Object(CakeRequest))
#8 C:\xampp\htdocs\portal\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(SectionsController), Object(CakeRequest), Object(CakeResponse))
#9 C:\xampp\htdocs\portal\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2014-07-22 21:27:21 Error: [MissingTableException] Table sections for model Section was not found in datasource default.
Exception Attributes: array (
  'table' => 'sections',
  'class' => 'Section',
  'ds' => 'default',
)
Request URL: /portal/sections
Stack Trace:
#0 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(3501): Model->setSource('sections')
#1 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(2905): Model->getDataSource()
#2 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(2877): Model->_readDataSource('all', Array)
#3 C:\xampp\htdocs\portal\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#4 C:\xampp\htdocs\portal\app\Controller\SectionsController.php(27): PaginatorComponent->paginate()
#5 [internal function]: SectionsController->index()
#6 C:\xampp\htdocs\portal\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(SectionsController), Array)
#7 C:\xampp\htdocs\portal\lib\Cake\Routing\Dispatcher.php(190): Controller->invokeAction(Object(CakeRequest))
#8 C:\xampp\htdocs\portal\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(SectionsController), Object(CakeRequest), Object(CakeResponse))
#9 C:\xampp\htdocs\portal\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2014-07-22 22:57:08 Error: [MissingTableException] Table sections for model Section was not found in datasource default.
Exception Attributes: array (
  'table' => 'sections',
  'class' => 'Section',
  'ds' => 'default',
)
Request URL: /portal/categories
Stack Trace:
#0 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(3501): Model->setSource('sections')
#1 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(1357): Model->getDataSource()
#2 C:\xampp\htdocs\portal\lib\Cake\Model\Datasource\DboSource.php(2481): Model->schema()
#3 C:\xampp\htdocs\portal\lib\Cake\Model\Datasource\DboSource.php(1706): DboSource->fields(Object(Section), 'Section', '')
#4 C:\xampp\htdocs\portal\lib\Cake\Model\Datasource\DboSource.php(1093): DboSource->generateAssociationQuery(Object(Category), Object(Section), 'belongsTo', 'Section', Array, Array, false)
#5 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(2905): DboSource->read(Object(Category), Array)
#6 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(2877): Model->_readDataSource('all', Array)
#7 C:\xampp\htdocs\portal\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#8 C:\xampp\htdocs\portal\app\Controller\CategoriesController.php(27): PaginatorComponent->paginate()
#9 [internal function]: CategoriesController->index()
#10 C:\xampp\htdocs\portal\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(CategoriesController), Array)
#11 C:\xampp\htdocs\portal\lib\Cake\Routing\Dispatcher.php(190): Controller->invokeAction(Object(CakeRequest))
#12 C:\xampp\htdocs\portal\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(CategoriesController), Object(CakeRequest), Object(CakeResponse))
#13 C:\xampp\htdocs\portal\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
2014-07-22 22:57:11 Error: [MissingTableException] Table sections for model Section was not found in datasource default.
Exception Attributes: array (
  'table' => 'sections',
  'class' => 'Section',
  'ds' => 'default',
)
Request URL: /portal/categories
Stack Trace:
#0 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(3501): Model->setSource('sections')
#1 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(1357): Model->getDataSource()
#2 C:\xampp\htdocs\portal\lib\Cake\Model\Datasource\DboSource.php(2481): Model->schema()
#3 C:\xampp\htdocs\portal\lib\Cake\Model\Datasource\DboSource.php(1706): DboSource->fields(Object(Section), 'Section', '')
#4 C:\xampp\htdocs\portal\lib\Cake\Model\Datasource\DboSource.php(1093): DboSource->generateAssociationQuery(Object(Category), Object(Section), 'belongsTo', 'Section', Array, Array, false)
#5 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(2905): DboSource->read(Object(Category), Array)
#6 C:\xampp\htdocs\portal\lib\Cake\Model\Model.php(2877): Model->_readDataSource('all', Array)
#7 C:\xampp\htdocs\portal\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#8 C:\xampp\htdocs\portal\app\Controller\CategoriesController.php(27): PaginatorComponent->paginate()
#9 [internal function]: CategoriesController->index()
#10 C:\xampp\htdocs\portal\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(CategoriesController), Array)
#11 C:\xampp\htdocs\portal\lib\Cake\Routing\Dispatcher.php(190): Controller->invokeAction(Object(CakeRequest))
#12 C:\xampp\htdocs\portal\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(CategoriesController), Object(CakeRequest), Object(CakeResponse))
#13 C:\xampp\htdocs\portal\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
2014-07-24 01:13:00 Error: [NotFoundException] Invalid user
Request URL: /news/users/view/navicat.png
Stack Trace:
#0 [internal function]: UsersController->view('navicat.png')
#1 C:\xampp\htdocs\news\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 C:\xampp\htdocs\news\lib\Cake\Routing\Dispatcher.php(190): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\news\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\news\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-07-24 01:22:07 Error: [NotFoundException] Invalid user
Request URL: /news/users/view/navicat.png
Stack Trace:
#0 [internal function]: UsersController->view('navicat.png')
#1 C:\xampp\htdocs\news\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 C:\xampp\htdocs\news\lib\Cake\Routing\Dispatcher.php(190): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\news\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\news\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-07-24 01:27:01 Error: [NotFoundException] Invalid user
Request URL: /news/users/view/navicat.png
Stack Trace:
#0 [internal function]: UsersController->view('navicat.png')
#1 C:\xampp\htdocs\news\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 C:\xampp\htdocs\news\lib\Cake\Routing\Dispatcher.php(190): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\news\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\news\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-07-24 01:41:31 Error: [MissingHelperException] Helper class UserHelper could not be found.
Exception Attributes: array (
  'class' => 'UserHelper',
  'plugin' => false,
)
Request URL: /news/users/edit/4
Stack Trace:
#0 C:\xampp\htdocs\news\lib\Cake\View\HelperCollection.php(63): HelperCollection->load('User')
#1 C:\xampp\htdocs\news\lib\Cake\View\View.php(832): HelperCollection->__isset('User')
#2 C:\xampp\htdocs\news\app\View\Users\edit.ctp(54): View->__get('User')
#3 C:\xampp\htdocs\news\lib\Cake\View\View.php(943): include('C:\xampp\htdocs...')
#4 C:\xampp\htdocs\news\lib\Cake\View\View.php(905): View->_evaluate('C:\xampp\htdocs...', Array)
#5 C:\xampp\htdocs\news\lib\Cake\View\View.php(465): View->_render('C:\xampp\htdocs...')
#6 C:\xampp\htdocs\news\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#7 C:\xampp\htdocs\news\lib\Cake\Routing\Dispatcher.php(197): Controller->render()
#8 C:\xampp\htdocs\news\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#9 C:\xampp\htdocs\news\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2014-07-24 02:05:18 Error: [NotFoundException] Invalid user
Request URL: /news/users/view/2014-03-09%2016.36.26.jpg
Stack Trace:
#0 [internal function]: UsersController->view('2014-03-09 16.3...')
#1 C:\xampp\htdocs\news\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 C:\xampp\htdocs\news\lib\Cake\Routing\Dispatcher.php(190): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\news\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\news\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-07-24 03:16:18 Error: Fatal Error (1): Unsupported operand types in [C:\xampp\htdocs\news\lib\Cake\View\Helper\HtmlHelper.php, line 804]
2014-07-24 03:16:18 Error: [FatalErrorException] Unsupported operand types
Request URL: /news/users/view/4
Stack Trace:
#0 C:\xampp\htdocs\news\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Unsupported ope...', 'C:\xampp\htdocs...', 804)
#1 [internal function]: ErrorHandler::handleError(1, 'Unsupported ope...', 'C:\xampp\htdocs...', 804, Array)
#2 C:\xampp\htdocs\news\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 1, 'Unsupported ope...', 'C:\xampp\htdocs...', 804, Array)
#3 C:\xampp\htdocs\news\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-07-24 03:18:53 Error: [MissingControllerException] Controller class ImgController could not be found.
Exception Attributes: array (
  'class' => 'ImgController',
  'plugin' => NULL,
)
Request URL: /news/img/files/photo/photo_dir/2014-03-09%2016.36.26.jpg
Stack Trace:
#0 C:\xampp\htdocs\news\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-07-24 03:53:00 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Array' in 'field list'
Request URL: /news/users/edit/4
Stack Trace:
#0 C:\xampp\htdocs\news\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\news\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('UPDATE `portal`...', Array)
#2 C:\xampp\htdocs\news\lib\Cake\Model\Datasource\Database\Mysql.php(411): DboSource->execute('UPDATE `portal`...')
#3 C:\xampp\htdocs\news\lib\Cake\Model\Model.php(1823): Mysql->update(Object(User), Array, Array)
#4 C:\xampp\htdocs\news\app\Controller\UsersController.php(41): Model->save(Array)
#5 [internal function]: UsersController->edit('4')
#6 C:\xampp\htdocs\news\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#7 C:\xampp\htdocs\news\lib\Cake\Routing\Dispatcher.php(190): Controller->invokeAction(Object(CakeRequest))
#8 C:\xampp\htdocs\news\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#9 C:\xampp\htdocs\news\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2014-07-24 03:55:52 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Array' in 'field list'
Request URL: /news/users/edit/4
Stack Trace:
#0 C:\xampp\htdocs\news\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\news\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('UPDATE `portal`...', Array)
#2 C:\xampp\htdocs\news\lib\Cake\Model\Datasource\Database\Mysql.php(411): DboSource->execute('UPDATE `portal`...')
#3 C:\xampp\htdocs\news\lib\Cake\Model\Model.php(1823): Mysql->update(Object(User), Array, Array)
#4 C:\xampp\htdocs\news\app\Controller\UsersController.php(41): Model->save(Array)
#5 [internal function]: UsersController->edit('4')
#6 C:\xampp\htdocs\news\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#7 C:\xampp\htdocs\news\lib\Cake\Routing\Dispatcher.php(190): Controller->invokeAction(Object(CakeRequest))
#8 C:\xampp\htdocs\news\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#9 C:\xampp\htdocs\news\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2014-07-24 03:56:20 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Array' in 'field list'
Request URL: /news/users/edit/4
Stack Trace:
#0 C:\xampp\htdocs\news\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\news\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('UPDATE `portal`...', Array)
#2 C:\xampp\htdocs\news\lib\Cake\Model\Datasource\Database\Mysql.php(411): DboSource->execute('UPDATE `portal`...')
#3 C:\xampp\htdocs\news\lib\Cake\Model\Model.php(1823): Mysql->update(Object(User), Array, Array)
#4 C:\xampp\htdocs\news\app\Controller\UsersController.php(41): Model->save(Array)
#5 [internal function]: UsersController->edit('4')
#6 C:\xampp\htdocs\news\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#7 C:\xampp\htdocs\news\lib\Cake\Routing\Dispatcher.php(190): Controller->invokeAction(Object(CakeRequest))
#8 C:\xampp\htdocs\news\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#9 C:\xampp\htdocs\news\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2014-07-24 04:02:00 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Array' in 'field list'
Request URL: /news/users/edit/4
Stack Trace:
#0 C:\xampp\htdocs\news\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\news\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('UPDATE `portal`...', Array)
#2 C:\xampp\htdocs\news\lib\Cake\Model\Datasource\Database\Mysql.php(411): DboSource->execute('UPDATE `portal`...')
#3 C:\xampp\htdocs\news\lib\Cake\Model\Model.php(1823): Mysql->update(Object(User), Array, Array)
#4 C:\xampp\htdocs\news\app\Controller\UsersController.php(41): Model->save(Array)
#5 [internal function]: UsersController->edit('4')
#6 C:\xampp\htdocs\news\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#7 C:\xampp\htdocs\news\lib\Cake\Routing\Dispatcher.php(190): Controller->invokeAction(Object(CakeRequest))
#8 C:\xampp\htdocs\news\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#9 C:\xampp\htdocs\news\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2014-07-24 17:12:46 Error: [MissingControllerException] Controller class ImgController could not be found.
Exception Attributes: array (
  'class' => 'ImgController',
  'plugin' => NULL,
)
Request URL: /news/img/files/photo/photo_dir/
Stack Trace:
#0 C:\xampp\htdocs\news\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-07-24 17:12:47 Error: [MissingControllerException] Controller class ImgController could not be found.
Exception Attributes: array (
  'class' => 'ImgController',
  'plugin' => NULL,
)
Request URL: /news/img/files/photo/photo_dir/
Stack Trace:
#0 C:\xampp\htdocs\news\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-07-24 17:12:56 Error: [MissingControllerException] Controller class ImgController could not be found.
Exception Attributes: array (
  'class' => 'ImgController',
  'plugin' => NULL,
)
Request URL: /news/img/files/photo/photo_dir/2014-03-09%2016.36.26.jpg
Stack Trace:
#0 C:\xampp\htdocs\news\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-07-24 17:12:57 Error: [MissingControllerException] Controller class ImgController could not be found.
Exception Attributes: array (
  'class' => 'ImgController',
  'plugin' => NULL,
)
Request URL: /news/img/files/photo/photo_dir/2014-03-09%2016.36.26.jpg
Stack Trace:
#0 C:\xampp\htdocs\news\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-07-24 17:15:11 Error: [MissingControllerException] Controller class ImgController could not be found.
Exception Attributes: array (
  'class' => 'ImgController',
  'plugin' => NULL,
)
Request URL: /news/img/files/photo/photo_dir/2014-03-09%2016.36.26.jpg
Stack Trace:
#0 C:\xampp\htdocs\news\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-07-24 17:49:37 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'username'
Request URL: /news/users/add
Stack Trace:
#0 C:\xampp\htdocs\news\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\news\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('INSERT INTO `po...', Array)
#2 C:\xampp\htdocs\news\lib\Cake\Model\Datasource\DboSource.php(1012): DboSource->execute('INSERT INTO `po...')
#3 C:\xampp\htdocs\news\lib\Cake\Model\Model.php(1834): DboSource->create(Object(User), Array, Array)
#4 C:\xampp\htdocs\news\app\Controller\UsersController.php(25): Model->save()
#5 [internal function]: UsersController->add()
#6 C:\xampp\htdocs\news\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#7 C:\xampp\htdocs\news\lib\Cake\Routing\Dispatcher.php(190): Controller->invokeAction(Object(CakeRequest))
#8 C:\xampp\htdocs\news\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#9 C:\xampp\htdocs\news\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2014-07-24 17:49:54 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'username'
Request URL: /news/users/add
Stack Trace:
#0 C:\xampp\htdocs\news\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\news\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('INSERT INTO `po...', Array)
#2 C:\xampp\htdocs\news\lib\Cake\Model\Datasource\DboSource.php(1012): DboSource->execute('INSERT INTO `po...')
#3 C:\xampp\htdocs\news\lib\Cake\Model\Model.php(1834): DboSource->create(Object(User), Array, Array)
#4 C:\xampp\htdocs\news\app\Controller\UsersController.php(25): Model->save()
#5 [internal function]: UsersController->add()
#6 C:\xampp\htdocs\news\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#7 C:\xampp\htdocs\news\lib\Cake\Routing\Dispatcher.php(190): Controller->invokeAction(Object(CakeRequest))
#8 C:\xampp\htdocs\news\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#9 C:\xampp\htdocs\news\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2014-07-24 17:50:18 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'username'
Request URL: /news/users/add
Stack Trace:
#0 C:\xampp\htdocs\news\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\news\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('INSERT INTO `po...', Array)
#2 C:\xampp\htdocs\news\lib\Cake\Model\Datasource\DboSource.php(1012): DboSource->execute('INSERT INTO `po...')
#3 C:\xampp\htdocs\news\lib\Cake\Model\Model.php(1834): DboSource->create(Object(User), Array, Array)
#4 C:\xampp\htdocs\news\app\Controller\UsersController.php(25): Model->save()
#5 [internal function]: UsersController->add()
#6 C:\xampp\htdocs\news\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#7 C:\xampp\htdocs\news\lib\Cake\Routing\Dispatcher.php(190): Controller->invokeAction(Object(CakeRequest))
#8 C:\xampp\htdocs\news\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#9 C:\xampp\htdocs\news\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2014-07-24 17:51:01 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'username'
Request URL: /news/users/add
Stack Trace:
#0 C:\xampp\htdocs\news\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\news\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('INSERT INTO `po...', Array)
#2 C:\xampp\htdocs\news\lib\Cake\Model\Datasource\DboSource.php(1012): DboSource->execute('INSERT INTO `po...')
#3 C:\xampp\htdocs\news\lib\Cake\Model\Model.php(1834): DboSource->create(Object(User), Array, Array)
#4 C:\xampp\htdocs\news\app\Controller\UsersController.php(25): Model->save()
#5 [internal function]: UsersController->add()
#6 C:\xampp\htdocs\news\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#7 C:\xampp\htdocs\news\lib\Cake\Routing\Dispatcher.php(190): Controller->invokeAction(Object(CakeRequest))
#8 C:\xampp\htdocs\news\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#9 C:\xampp\htdocs\news\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
